spring:
  activemq:
    broker-url : tcp://localhost:61616
    user: admin
    password: admin
    packages:
      trust-all: true
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      password: 123456
      timeout: 60000


mode:
  async: false
  epsilon: 2


companies:
  network:
    company_A: company_B, company_D
    company_B: company_A, company_C, company_E
    company_C: company_B, company_E
    company_D: company_A, company_E
    company_E: company_C, company_D, company_B
  response-queue-config:
    company_A: company_A_response
    company_B: company_B_response
    company_C: company_C_response
    company_D: company_D_response
    company_E: company_E_response
